# Generated by Django 5.1.6 on 2025-02-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounterParties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('marka_auto', models.CharField(max_length=50)),
                ('number_auto', models.CharField(max_length=50)),
                ('vin_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Контрагента в список',
                'verbose_name_plural': 'Список контрагентов',
            },
        ),
    ]
