# Generated by Django 5.1.6 on 2025-03-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparties',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='counterparties',
            name='marka_auto',
        ),
        migrations.RemoveField(
            model_name='counterparties',
            name='number_auto',
        ),
        migrations.RemoveField(
            model_name='counterparties',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='counterparties',
            name='vin_number',
        ),
        migrations.AddField(
            model_name='counterparties',
            name='inn',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.CreateModel(
            name='CounterpartyCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('number_auto', models.CharField(max_length=50)),
                ('vin_number', models.CharField(max_length=50)),
                ('marka_auto', models.CharField(max_length=50)),
                ('model_auto', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=50)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='counterparties.counterparties')),
            ],
            options={
                'verbose_name': 'Машину в список к контрагенту',
                'verbose_name_plural': 'Список машин контрагентов',
            },
        ),
    ]
