# Generated by Django 5.1.6 on 2025-03-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0003_counterparties_author_counterparties_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparties',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
