# Generated by Django 5.1.6 on 2025-02-13 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_auto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гос. Номера авто')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('date_entry', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время ВЪЕЗДА доставки')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус - Завешена')),
                ('date_exit', models.DateTimeField(blank=True, null=True, verbose_name='Время ВЫЕЗДА доставки')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_delivery', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_delivery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доставку',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.CreateModel(
            name='EntryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_auto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гос. Номер авто')),
                ('marka_auto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Марка авто')),
                ('name_organization', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование организции')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата въезда')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время въезда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='Вьезд разрешён или запрещён')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус - Завешена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_entry_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Машину на въезд',
                'verbose_name_plural': 'Машины на въезд',
            },
        ),
        migrations.CreateModel(
            name='ExitTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_auto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гос. Номер авто')),
                ('marka_auto', models.CharField(max_length=50, verbose_name='Марка авто')),
                ('name_organization', models.CharField(max_length=50, verbose_name='Наименование организции')),
                ('date', models.DateField(verbose_name='Дата выезда')),
                ('time', models.TimeField(verbose_name='Время выезда')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('is_allowed', models.BooleanField(default=True, verbose_name='Выезд разрешён или запрещён')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус - Завешена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_exit_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Машину на выезд',
                'verbose_name_plural': 'Машины на выезд',
            },
        ),
        migrations.CreateModel(
            name='KontragentTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_auto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гос. Номера авто')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('date_entry', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время ВЪЕЗДА контрагента')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус - Завешена')),
                ('date_exit', models.DateTimeField(blank=True, null=True, verbose_name='Время ВЫЕЗДА контрагента')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_kontragent', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_kontragent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Контрагента',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='TextTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок задачи')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='Текст задачи')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата публикации задачи')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время публикации задачи')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус - Завешена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Текстовую задачу',
                'verbose_name_plural': 'Текстовые задачи',
            },
        ),
    ]
