# Generated by Django 5.1.6 on 2025-02-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytasks',
            name='number_auto',
            field=models.CharField(max_length=50, null=True, verbose_name='Гос. Номера авто'),
        ),
        migrations.AlterField(
            model_name='entrytasks',
            name='marka_auto',
            field=models.CharField(max_length=50, null=True, verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='entrytasks',
            name='name_organization',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование организции'),
        ),
        migrations.AlterField(
            model_name='entrytasks',
            name='number_auto',
            field=models.CharField(max_length=50, null=True, verbose_name='Гос. Номер авто'),
        ),
        migrations.AlterField(
            model_name='exittasks',
            name='marka_auto',
            field=models.CharField(max_length=50, null=True, verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='exittasks',
            name='name_organization',
            field=models.CharField(max_length=50, null=True, verbose_name='Наименование организции'),
        ),
        migrations.AlterField(
            model_name='exittasks',
            name='number_auto',
            field=models.CharField(max_length=50, null=True, verbose_name='Гос. Номер авто'),
        ),
        migrations.AlterField(
            model_name='kontragenttasks',
            name='number_auto',
            field=models.CharField(max_length=50, null=True, verbose_name='Гос. Номера авто'),
        ),
    ]
