# Generated by Django 5.1.6 on 2025-02-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_deliverytasks_number_auto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrytasks',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата въезда'),
        ),
        migrations.AlterField(
            model_name='entrytasks',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время въезда'),
        ),
    ]
