# Generated by Django 5.1.6 on 2025-02-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_entrytasks_date_alter_entrytasks_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exittasks',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='exittasks',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время выезда'),
        ),
        migrations.AlterField(
            model_name='texttasks',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата публикации задачи'),
        ),
        migrations.AlterField(
            model_name='texttasks',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время публикации задачи'),
        ),
    ]
