# Generated by Django 5.1.6 on 2025-03-10 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcar',
            options={'verbose_name': 'Новую машину', 'verbose_name_plural': 'Новые машины'},
        ),
        migrations.AddField(
            model_name='newcar',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newcar',
            name='date_entry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newcar',
            name='date_exit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newcar',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
